/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 f4.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function F4(props) {
  const { nodes, materials } = useGLTF("/mesh/f4.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.274, -0.402, 1.615]}
        rotation={[3.105, 0, -Math.PI / 2]}
        scale={[-0.165, -1, -0.625]}
      >
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.Body} />
        <mesh
          geometry={nodes.Circle002_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Circle002_3.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Circle002_4.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[0.031, -0.009, 3.675]}
        rotation={[Math.PI / 2, -Math.PI / 4, 0]}
        scale={[0.13, 0.033, 0.13]}
      >
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cylinder003_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[0.004, -0.7, 2.162]}
        scale={0.176}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-0.11, 0.822, 1.82]}
        scale={[0.02, 0.025, 0.02]}
      />
    </group>
  );
}

useGLTF.preload("/mesh/f4.glb");
