/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mario_obj.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function MarioBros(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/mesh/mario_obj.glb");
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    actions?.jump.play();
  }, []);

  useFrame(() => {
    if (mixer.time > 0.8) {
      actions?.jump.halt();
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Player">
        <group name="Player_1">
          <group name="Mario">
            <group name="AllRoot">
              <group name="JointRoot" position={[0, 0.611, -0.041]}>
                <primitive object={nodes.Hip} />
                <primitive object={nodes.Spine1} />
              </group>
            </group>
            <skinnedMesh
              name="Face00__MarioFaceMat00"
              geometry={nodes.Face00__MarioFaceMat00.geometry}
              material={materials.MarioFaceMat00}
              skeleton={nodes.Face00__MarioFaceMat00.skeleton}
            >
              <skinnedMesh
                name="Face00__MarioHigeMat00"
                geometry={nodes.Face00__MarioHigeMat00.geometry}
                material={materials.MarioHigeMat00}
                skeleton={nodes.Face00__MarioHigeMat00.skeleton}
              />
            </skinnedMesh>
            <skinnedMesh
              name="Mario__MarioBodyMat00"
              geometry={nodes.Mario__MarioBodyMat00.geometry}
              material={materials.MarioBodyMat00}
              skeleton={nodes.Mario__MarioBodyMat00.skeleton}
            >
              <skinnedMesh
                name="Mario__MarioBodyMat01"
                geometry={nodes.Mario__MarioBodyMat01.geometry}
                material={materials.MarioBodyMat01}
                skeleton={nodes.Mario__MarioBodyMat01.skeleton}
              />
              <skinnedMesh
                name="Mario__MarioFaceMat00"
                geometry={nodes.Mario__MarioFaceMat00.geometry}
                material={materials.MarioMetalMat00}
                skeleton={nodes.Mario__MarioFaceMat00.skeleton}
              />
              <skinnedMesh
                name="Mario__MarioMetalMat00"
                geometry={nodes.Mario__MarioMetalMat00.geometry}
                material={materials.MarioMetalMat00}
                skeleton={nodes.Mario__MarioMetalMat00.skeleton}
              />
              <skinnedMesh
                name="Mario__MarioShoesMat00"
                geometry={nodes.Mario__MarioShoesMat00.geometry}
                material={materials.MarioShoesMat00}
                skeleton={nodes.Mario__MarioShoesMat00.skeleton}
              />
            </skinnedMesh>
            <skinnedMesh
              name="Eyeball__MarioEyeMat00"
              geometry={nodes.Eyeball__MarioEyeMat00.geometry}
              material={materials.MarioEyeMat00}
              skeleton={nodes.Eyeball__MarioEyeMat00.skeleton}
            />
            <skinnedMesh
              name="HandL00__MarioHandMat00"
              geometry={nodes.HandL00__MarioHandMat00.geometry}
              material={materials.MarioHandMat00}
              skeleton={nodes.HandL00__MarioHandMat00.skeleton}
            />
            <skinnedMesh
              name="HandR00__MarioHandMat00"
              geometry={nodes.HandR00__MarioHandMat00.geometry}
              material={materials.MarioHandMat00}
              skeleton={nodes.HandR00__MarioHandMat00.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mesh/mario_obj.glb");
