/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 star_wars_x-wing.glb --transform 
Files: star_wars_x-wing.glb [3.25MB] > /Users/lunakepio/dev/death-star/public/models/ships/star_wars_x-wing-transformed.glb [212.94KB] (93%)
Author: Daniel (https://sketchfab.com/DanielAndersson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-x-wing-a93f607a94d747568371b8910a81fb12
Title: Star Wars: X-Wing
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { Flame } from "./Flame";

export function Ship({ wingsOpen = true, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/mesh/xWing.glb");
  const { actions } = useAnimations(animations, group);
  const engineColor = "#d260fe";

  const wingOne = useRef();
  const wingTwo = useRef();
  const wingThree = useRef();
  const wingFour = useRef();
  const wingsOpening = Math.PI / 14;

  useGSAP(() => {
    if (!wingsOpen) {
      gsap.to(wingOne.current.rotation, { y: 0, duration: 1 });
      gsap.to(wingTwo.current.rotation, { y: 0, duration: 1 });
      gsap.to(wingThree.current.rotation, { y: 0, duration: 1 });
      gsap.to(wingFour.current.rotation, { y: 0, duration: 1 });
    }
    if (wingsOpen) {
      gsap.to(wingOne.current.rotation, { y: wingsOpening, duration: 1 });
      gsap.to(wingTwo.current.rotation, { y: -wingsOpening, duration: 1 });
      gsap.to(wingThree.current.rotation, { y: wingsOpening, duration: 1 });
      gsap.to(wingFour.current.rotation, { y: -wingsOpening, duration: 1 });
    }
  }, [wingsOpen]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="X-Wing" rotation={[-Math.PI / 2, 0, 0]} scale={8.333}>
          <group name="WingRotation" position={[0, -1.405, -0.012]} />
          <group name="LeftWingBottom" position={[0, 0, -0.012]} ref={wingOne}>
            <Flame position={[0.157, 0.76, -0.092]} />
            <group name="LeftWingBottomHullPlates">
              <mesh
                receiveShadow
                castShadow
                name="LeftWingBottomHullPlates_0"
                geometry={nodes.LeftWingBottomHullPlates_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <group name="LeftWingBottomEngineAndGreebles">
              <mesh
                receiveShadow
                castShadow
                name="LeftWingBottomEngineAndGreebles_0"
                geometry={nodes.LeftWingBottomEngineAndGreebles_0.geometry}
                material={materials.PaletteMaterial001}
              />
              <mesh
                receiveShadow
                castShadow
                name="LeftWingBottomEngineAndGreebles_3"
                geometry={nodes.LeftWingBottomEngineAndGreebles_3.geometry}
              >
                <meshStandardMaterial
                  attach="material"
                  emissive={engineColor}
                />
              </mesh>
            </group>
            <mesh
              receiveShadow
              castShadow
              name="LeftWingBottom_0"
              geometry={nodes.LeftWingBottom_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group name="LeftWingTop" position={[0, 0, -0.012]} ref={wingTwo}>
            <Flame position={[0.157, 0.76, 0.095]} />

            <group name="LeftWingTopHullPlates">
              <mesh
                name="LeftWingTopHullPlates_0"
                geometry={nodes.LeftWingTopHullPlates_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <group name="LeftWingTopEngineAndGreebles">
              <mesh
                receiveShadow
                castShadow
                name="LeftWingTopEngineAndGreebles_0"
                geometry={nodes.LeftWingTopEngineAndGreebles_0.geometry}
                material={materials.PaletteMaterial001}
              />
              <mesh
                receiveShadow
                castShadow
                name="LeftWingTopEngineAndGreebles_3"
                geometry={nodes.LeftWingTopEngineAndGreebles_3.geometry}
              >
                <meshStandardMaterial
                  attach="material"
                  emissive={engineColor}
                />
              </mesh>
            </group>
            <mesh
              receiveShadow
              castShadow
              name="LeftWingTop_0"
              geometry={nodes.LeftWingTop_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group name="RightWingTop" position={[0, 0, -0.012]} ref={wingThree}>
            <Flame position={[-0.157, 0.76, 0.095]} />

            <group name="RightWingTopEngineAndGreebles">
              <mesh
                receiveShadow
                castShadow
                name="RightWingTopEngineAndGreebles_0"
                geometry={nodes.RightWingTopEngineAndGreebles_0.geometry}
                material={materials.PaletteMaterial001}
              />
              <mesh
                receiveShadow
                castShadow
                name="RightWingTopEngineAndGreebles_3"
                geometry={nodes.RightWingTopEngineAndGreebles_3.geometry}
              >
                <meshStandardMaterial
                  attach="material"
                  emissive={engineColor}
                />
              </mesh>
            </group>
            <group name="RightWingTopHullPlates">
              <mesh
                receiveShadow
                castShadow
                name="RightWingTopHullPlates_0"
                geometry={nodes.RightWingTopHullPlates_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              receiveShadow
              castShadow
              name="RightWingTop_0"
              geometry={nodes.RightWingTop_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
          <group
            name="RightWingBottom"
            position={[0, 0, -0.012]}
            ref={wingFour}
          >
            <Flame position={[-0.157, 0.76, -0.092]} />

            <group name="RightWingBottomEngineAndGreebles">
              <mesh
                receiveShadow
                castShadow
                name="RightWingBottomEngineAndGreebles_0"
                geometry={nodes.RightWingBottomEngineAndGreebles_0.geometry}
                material={materials.PaletteMaterial001}
              />
              <mesh
                receiveShadow
                castShadow
                name="RightWingBottomEngineAndGreebles_3"
                geometry={nodes.RightWingBottomEngineAndGreebles_3.geometry}
              >
                <meshStandardMaterial
                  attach="material"
                  emissive={engineColor}
                />
              </mesh>
            </group>
            <group name="RightWingBottomHullPlates">
              <mesh
                receiveShadow
                castShadow
                name="RightWingBottomHullPlates_0"
                geometry={nodes.RightWingBottomHullPlates_0.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
            <mesh
              receiveShadow
              castShadow
              name="RightWingBottom_0"
              geometry={nodes.RightWingBottom_0.geometry}
              material={materials.PaletteMaterial001}
            />
          </group>
        </group>
        <mesh
          receiveShadow
          castShadow
          name="CentralSection_0"
          geometry={nodes.CentralSection_0.geometry}
          material={materials.PaletteMaterial001}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.333}
        />
        <mesh
          receiveShadow
          castShadow
          name="CentralSection_1"
          geometry={nodes.CentralSection_1.geometry}
          material={materials.PaletteMaterial002}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.333}
        />
        <mesh
          receiveShadow
          castShadow
          name="R2Head_3"
          geometry={nodes.R2Head_3.geometry}
          material={materials.PaletteMaterial003}
          position={[0, 0.713, -1.406]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={8.333}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mesh/xWing.glb");
